use university;


INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (1,100,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (2,101,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (3,102,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (4,103,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (5,104,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (6,105,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (7,106,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (8,107,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (9,108,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (10,109,1,'Math');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (11,110,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (12,111,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (13,112,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (14,113,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (15,114,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (16,115,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (17,116,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (18,117,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (19,118,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (20,119,1,'Math');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (21,120,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (22,121,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (23,122,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (24,123,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (25,124,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (26,125,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (27,126,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (28,127,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (29,128,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (30,129,1,'Math');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (31,130,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (32,131,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (33,132,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (34,133,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (35,134,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (36,135,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (37,136,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (38,137,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (39,138,1,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (40,139,1,'Math');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (41,200,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (42,201,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (43,202,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (44,203,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (45,204,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (46,205,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (47,206,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (48,207,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (49,208,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (50,209,2,'Math');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (51,210,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (52,211,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (53,212,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (54,213,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (55,214,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (56,215,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (57,216,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (58,217,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (59,218,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (60,219,2,'Math');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (61,220,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (62,221,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (63,222,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (64,223,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (65,224,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (66,225,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (67,226,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (68,227,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (69,228,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (70,229,2,'Math');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (71,230,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (72,231,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (73,232,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (74,233,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (75,234,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (76,235,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (77,236,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (78,237,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (79,238,2,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (80,239,2,'Math');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (81,300,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (82,301,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (83,302,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (84,303,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (85,304,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (86,305,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (87,306,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (88,307,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (89,308,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (90,309,3,'Math');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (91,310,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (92,311,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (93,312,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (94,313,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (95,314,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (96,315,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (97,316,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (98,317,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (99,318,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (100,319,3,'Math');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (101,320,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (102,321,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (103,322,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (104,323,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (105,324,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (106,325,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (107,326,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (108,327,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (109,328,3,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (110,329,3,'Math');

INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (111,400,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (112,401,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (113,402,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (114,403,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (115,404,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (116,405,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (117,406,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (118,407,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (119,408,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (120,409,4,'Math');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (121,410,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (122,411,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (123,412,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (124,413,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (125,414,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (126,415,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (127,416,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (128,417,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (129,418,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (130,419,4,'Math');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (131,420,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (132,421,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (133,422,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (134,423,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (135,424,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (136,425,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (137,426,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (138,427,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (139,428,4,'Math'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (140,429,4,'Math');


INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (150,100,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (151,101,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (152,102,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (153,103,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (154,104,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (155,105,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (156,106,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (157,107,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (158,108,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (159,109,1,'Physics');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (160,110,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (161,111,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (162,112,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (163,113,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (164,114,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (165,115,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (166,116,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (167,117,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (168,118,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (169,119,1,'Physics');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (170,120,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (171,121,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (172,122,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (173,123,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (174,124,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (175,125,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (176,126,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (177,127,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (178,128,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (179,129,1,'Physics');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (180,130,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (181,131,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (182,132,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (183,133,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (184,134,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (185,135,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (186,136,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (187,137,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (188,138,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (189,139,1,'Physics');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (190,140,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (191,141,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (192,142,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (193,143,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (194,144,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (195,145,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (196,146,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (197,147,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (198,148,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (199,149,1,'Physics');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (200,150,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (201,151,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (202,152,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (203,153,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (204,154,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (205,155,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (206,156,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (207,157,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (208,158,1,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (209,159,1,'Physics');

INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (210,200,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (211,201,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (212,202,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (213,203,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (214,204,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (215,205,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (216,206,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (217,207,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (218,208,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (219,209,2,'Physics');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (220,210,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (221,211,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (222,212,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (223,213,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (224,214,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (225,215,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (226,216,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (227,217,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (228,218,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (229,219,2,'Physics');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (230,220,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (231,221,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (232,222,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (233,223,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (234,224,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (235,225,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (236,226,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (237,227,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (238,228,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (239,229,2,'Physics');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (240,230,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (241,231,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (242,232,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (243,233,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (244,234,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (245,235,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (246,236,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (247,237,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (248,238,2,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (249,239,2,'Physics');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (250,300,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (251,301,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (252,302,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (253,303,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (254,304,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (255,305,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (256,306,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (257,307,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (258,308,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (259,309,3,'Physics');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (260,310,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (261,311,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (262,312,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (263,313,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (264,314,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (265,315,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (266,316,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (267,317,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (268,318,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (269,319,3,'Physics');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (270,320,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (271,321,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (272,322,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (273,323,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (274,324,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (275,325,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (276,326,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (277,327,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (278,328,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (279,329,3,'Physics');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (280,330,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (281,331,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (282,332,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (283,333,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (284,334,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (285,335,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (286,336,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (287,337,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (288,338,3,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (289,339,3,'Physics');

INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (290,400,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (291,401,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (292,402,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (293,403,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (294,404,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (295,405,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (296,406,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (297,407,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (298,408,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (299,409,4,'Physics');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (300,410,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (301,411,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (302,412,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (303,413,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (304,414,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (305,415,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (306,416,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (307,417,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (308,418,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (309,419,4,'Physics');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (310,420,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (311,421,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (312,422,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (313,423,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (314,424,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (315,425,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (316,426,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (317,427,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (318,428,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (319,429,4,'Physics');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (320,430,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (321,431,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (322,432,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (323,433,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (324,434,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (325,435,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (326,436,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (327,437,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (328,438,4,'Physics'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (329,439,4,'Physics');

INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (350,100,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (351,101,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (352,102,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (353,103,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (354,104,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (355,105,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (356,106,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (357,107,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (358,108,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (359,109,1,'IT');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (360,110,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (361,111,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (362,112,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (363,113,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (364,114,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (365,115,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (366,116,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (367,117,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (368,118,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (369,119,1,'IT');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (370,120,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (371,121,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (372,122,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (373,123,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (374,124,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (375,125,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (376,126,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (377,127,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (378,128,1,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (379,129,1,'IT');

INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (380,200,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (381,201,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (382,202,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (383,203,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (384,204,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (385,205,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (386,206,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (387,207,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (388,208,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (389,209,2,'IT');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (390,210,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (391,211,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (392,212,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (393,213,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (394,214,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (395,215,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (396,216,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (397,217,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (398,218,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (399,219,2,'IT');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (400,220,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (401,221,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (402,222,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (403,223,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (404,224,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (405,225,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (406,226,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (407,227,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (408,228,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (409,229,2,'IT');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (410,230,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (411,231,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (412,232,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (413,233,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (414,234,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (415,235,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (416,236,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (417,237,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (418,238,2,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (419,239,2,'IT');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (420,300,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (421,301,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (422,302,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (423,303,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (424,304,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (425,305,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (426,306,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (427,307,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (428,308,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (429,309,3,'IT');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (430,310,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (431,311,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (432,312,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (433,313,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (434,314,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (435,315,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (436,316,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (437,317,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (438,318,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (439,319,3,'IT');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (440,320,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (441,321,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (442,322,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (443,323,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (444,324,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (445,325,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (446,326,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (447,327,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (448,328,3,'IT'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (449,329,3,'IT');

INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (500,100,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (501,101,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (502,102,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (503,103,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (504,104,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (505,105,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (506,106,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (507,107,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (508,108,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (509,109,1,'Biology');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (510,110,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (511,111,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (512,112,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (513,113,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (514,114,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (515,115,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (516,116,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (517,117,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (518,118,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (519,119,1,'Biology');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (520,120,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (521,121,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (522,122,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (523,123,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (524,124,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (525,125,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (526,126,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (527,127,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (528,128,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (529,129,1,'Biology');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (530,130,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (531,131,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (532,132,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (533,133,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (534,134,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (535,135,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (536,136,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (537,137,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (538,138,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (539,139,1,'Biology');

INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (540,200,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (541,201,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (542,202,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (543,203,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (544,204,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (545,205,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (546,206,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (547,207,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (548,208,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (549,209,1,'Biology');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (550,210,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (551,211,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (552,212,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (553,213,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (554,214,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (555,215,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (556,216,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (557,217,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (558,218,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (559,219,1,'Biology');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (560,220,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (561,221,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (562,222,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (563,223,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (564,224,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (565,225,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (566,226,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (567,227,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (568,228,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (569,229,1,'Biology');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (570,230,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (571,231,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (572,232,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (573,233,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (574,234,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (575,235,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (576,236,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (577,237,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (578,238,1,'Biology'); INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (579,239,1,'Biology');



INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (580,100,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (581,101,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (582,102,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (583,103,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (584,104,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (585,105,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (586,106,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (587,107,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (588,108,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (589,109,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (590,110,1,'Main Building');
                                                                         
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (591,101,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (592,102,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (593,103,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (594,104,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (595,105,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (596,106,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (597,107,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (598,108,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (599,109,1,'Main Building');
INSERT INTO Room (RoomID,RoomNum,Floor,Building) VALUES (600,110,1,'Main Building');
